services:
  webserver:
    container_name: web-server
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d/:/etc/nginx/conf.d/:ro
      - ./sites-enabled/:/etc/nginx/sites-enabled