services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public/:/var/www/html/
      - ./nginx/:/etc/nginx/
      - ./letsencrypt/:/etc/letsencrypt/
    command: "./nginx/init.sh"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./public/:/var/www/html/
      - ./nginx/:/etc/nginx/
      - ./letsencrypt/:/etc/letsencrypt/
    command: "./letsencrypt/init.sh"