services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./public/:/var/www/html/
      - ./nginx/:/etc/nginx/
      - ./letsencrypt/:/etc/letsencrypt/
    command: /bin/sh -c "chmod +x /etc/nginx/init.sh && /etc/nginx/init.sh"
    restart: unless-stopped
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./public/:/var/www/html/
      - ./nginx/:/etc/nginx/
      - ./letsencrypt/:/etc/letsencrypt/
    command: /bin/sh -c "chmod +x /etc/letsencrypt/init.sh && /etc/letsencrypt/init.sh"