version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./public/:/usr/share/nginx/html/
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    command:
      - certbot
      - certonly
      - --webroot
      - -w
      - /var/www/certbot
      - --agree-tos
      - --no-eff-email
      - -d
      - james-hamilton.uk
      - -d
      - jameshamiltondata.com
      - -d
      - jameshamiltonenergy.com
      - --cert-name
      - jameshamilton