version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./public/:/var/www/html/
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    command: ["--webroot", "-w", "/var/www/certbot", "--nginx", "--agree-tos", "--no-eff-email", "-d", "james-hamilton.uk", "-d", "jameshamiltondata.com", "-d", "jameshamiltonenergy.com", "--cert-name", "jameshamilton"]